In [1]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

In [2]:
model=load_model("modelvggacc99_val_99.h5")

Model is Trained to predict 2 classes Real and Forged
* 0:- Real Image
* 1:- Forged Image

# Testing Real Image

In [3]:
image = load_img("01_049.png", target_size=(224, 224))
image = img_to_array(image)
image = image/255.0
image = np.expand_dims(image, axis = 0)

In [4]:
pred = model.predict(image)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
1/1 [==============================] - 1s 501ms/step


In [5]:
pred

array([[1.000000e+00, 6.887178e-10]], dtype=float32)

In [6]:
predict =np.argmax(pred,axis=1)

In [7]:
predict

array([0], dtype=int64)

# Testing Fake Image

In [8]:
image = load_img("01_0114049.PNG", target_size=(224, 224))
image = img_to_array(image)
image = image/255.0
image = np.expand_dims(image, axis = 0)

In [9]:
pred = model.predict(image)
predict =np.argmax(pred,axis=1)
predict

1/1 [==============================] - 0s 263ms/step


array([1], dtype=int64)